export interface R1000Model{
    TP_OPER: string,
    NM_LAYOUT: string,
    CD_SIS_ORIG: string,
    DT_MOVIMENT: string,
    TP_INSCRI: string,
    NR_INSCRI: string,
    DT_INI_VAL: string,
    DT_FIM_VAL: string,
    CD_CLASSTRIB: string,
    IN_ESCRITUR: string,
    IN_DESONERA: string,
    IN_ACO_MULT: string,
    IN_SIT_PJ: string,
    NM_RESP_CON: string,
    CD_CPF_CON: string,
    CD_TEL_CON: string,
    CD_CEL_CON: string,
    NM_EMAIL_CON: string,
    CD_CNPJ_EMP: string,
    NM_RAZAO_EMP: string,
    NM_CON_EMP: string,
    CD_TEL_EMP: string,
    NM_EMAIL_EMP: string,
    ID_EFR: string,
    CD_CNPJ_EFR: string,
    FILLER: string
}