export interface R1070Model{
    TP_OPER: string,
    NM_LAYOUT: string,
    CD_SIS_ORIG: string,
    DT_MOVIMENT: string,
    TP_INSCRI: string,
    NR_INSCRI: string,
    TP_PROCES: string,
    NR_PROCES: string,
    DT_INI_VAL: string,
    DT_FIM_VAL: string,
    IN_AUTORIA: string,
    CD_SUSPEN: string,
    IN_SUSPEN: string,
    DT_DECISAO: string,
    IN_DEPOSIT: string,
    CD_UF: string,
    CD_MUNIC: string,
    CD_VARA: string,
    IND_PROCES: string,
    REG_INCONS: string,
    BATE_INCONS: string,
    CD_ITGR: string,
    NR_SEQU_ITGR: string,
    CD_SITU_ITGR: string,
    DT_CTRL_ITGR: string,
    FILLER: string
}